# Generated by Django 5.2.4 on 2025-09-18 14:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0002_task_task_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="due_date",
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
